WIP: make it work on litex
  * litex platform does not use ns16550 at all
    so debug_ll_ns16550_init should be eliminated;

  * there is no IH_ARCH_RISCV definition in include/image.h
    at the moment, so the error stops compiling:
        common/bootm.c: In function 'bootm_open_os_uimage':
        common/bootm.c:491:34: error: 'IH_ARCH' undeclared (first use in this
        function)
        if (data->os->header.ih_arch != IH_ARCH) {
                                        ^~~~~~~

Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>